[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/pmorie/go-open-service-broker-client"
  version = "0.0.10"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.23.2"

[[constraint]]
  branch = "master"
  name = "github.com/pmorie/osb-broker-lib"

[[constraint]]
  branch = "basic_auth"
  name = "github.com/jaymccon/osb-broker-lib"
