image: awsservicebroker/aws-servicebroker:beta
imagePullPolicy: Always
authenticate: true
tls:
  cert:
  key:
deployClusterServiceBroker: true
deployNamespacedServiceBroker: false
aws:
  region: us-east-1
  bucket: awsservicebroker
  key: templates/latest
  s3region: us-east-1
  tablename: awssb
  accesskeyid: ""
  secretkey: ""
  targetaccountid: ""
  targetrolename: ""
  vpcid: ""
  existingSecret: ""
  accesskeyidName: "accesskeyid"
  secretkeyName: "secretkey"
brokerconfig:
  verbosity: 10
  brokerid: awsservicebroker
  prescribeoverrides: true
annotations: {}
clusterDomain: cluster.local

# Allow overridding the .Capabilities.KubeVersion.GitVersion (useful for "helm template" command)
kubeTargetVersionOverride: ""

# Add any extra environment variables to the deployment
extraEnv: []

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}